name: 'AI Code Reviewer'
description: 'A GitHub Action to review your code.'
author: 'Leandro Sbrissa'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'


runs:
  using: 'node20'
  main: 'dist/index.js'
