name: 'AI Code Reviewer'
description: 'Action do GitHub para revisar seu código.'
author: 'Leandro Sbrissa'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  GITHUB_TOKEN:
    description: "Token do GitHub para interagir com o repositório."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_ASSISTANT_ID:
    description: "OpenAI Assistant ID"
    required: true
    default: ""
  model:
    description: "Modelo de linguagem para análise de código"
    required: false
    default: "gpt-4-turbo"
  exclude:
    description: "Glob patterns para excluir arquivos da análise de diff"
    required: false
    default: ""
  language:
    description: "Idioma dos comentários"
    required: false
    default: "pt-br"
  MYSQL_URL:
    description: "URL do banco de dados MySQL"
    required: true

outputs:
  countFiles:
    description: 'Quantidade de arquivos analisados'
  countComments:
    description: 'Quantidade de comentários feitos'
  commentUrl:
    description: 'URL do comentário feito'

runs:
  using: 'node20'
  main: 'dist/index.js'
