name: 'AI Code Reviewer'
description: 'A GitHub Action to review your code.'
author: 'Leandro Sbrissa'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_ASSISTANT_ID:
    description: "OpenAI Assistant ID"
    required: true
    default: ""

# Define your outputs here.
outputs:
  countFiles:
    description: 'Quantidade de arquivos analisados'
  countComments:
    description: 'Quantidade de comentários feitos'


runs:
  using: 'node20'
  main: 'dist/index.js'
