on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    name: AI Action Code Reviewer
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: ./ # Uses an action in the root directory
        id: aireviewer
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exclude: '**/*.json, **/*.md, **/*.map'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.aireviewer.outputs.time }}"
