on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: AI Action Code Reviewer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: ./ # Uses an action in the root directory
        id: aireviewer
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
          exclude: '**/*.json, **/*.md, **/*.txt, **/*.map, **/*.lock, **/*.lock.json, **/*.log, **/*.log.*, **/dist/**, **/docs/**, **/build/**, **/volumes/**'
          MYSQL_URL: ${{ secrets.MYSQL_URL }}

      # Use the output from the `hello` step
      - name: Get the output
        run: echo "OUTPUT FILES=${{ steps.aireviewer.outputs.countFiles }}"
